# Generated by Django 3.1.4 on 2023-08-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('JEEP', 'JEEP'), ('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('COUPE', 'COUPE'), ('WAGON', 'WAGON')], max_length=15)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('power', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='cars')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
