# Generated by Django 3.1.4 on 2023-08-04 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='news_images')),
                ('description', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
