# Generated by Django 3.1.4 on 2023-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='category',
            field=models.CharField(max_length=300),
        ),
    ]
