# Generated by Django 3.1.4 on 2023-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
        ),
    ]
