# Generated by Django 3.1.4 on 2023-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TURER', 'TURER'), ('CROSS', 'CROSS'), ('SPORT', 'SPORT')], max_length=15)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('power', models.FloatField(max_length=25)),
                ('image', models.ImageField(upload_to='motorbikes_images')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
