# Generated by Django 3.1.4 on 2023-08-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooters',
            name='category',
            field=models.CharField(choices=[('20 MPH SCOOTERS', '20 MPH SCOOTERS'), ('30 MPH SCOOTERS', '30 MPH SCOOTERS'), ('40 MPH SCOOTERS', '40 MPH SCOOTERS'), ('50 MPH SCOOTERS', '50 MPH SCOOTERS')], max_length=15),
        ),
    ]
